name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: xvfb-run mvn -B test